SELECT ?item ?itemLabel 
WHERE 
{
  ?item wdt:P31 wd:Q5119.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } # Helps get the label in your language, if not, then en language
}

